language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r mumuni-springbootToy *
  - mkdir -p deploy
  - mv mumuni-springbootToy.zip deploy/mumuni-springbootToy.zip

deploy:
  - provider: s3
    access_ksy_id: $AWS_ACCESS_KEY # travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # travis repo setting 설정값
    bucket: mumuni-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 접근 권한을 private로 변경
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - ohj8447@gmail.com