language: java
jdk:
  - openjdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/mumuni-springbootToy.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # travis repo setting 설정값
    bucket: mumuni-springboot-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 접근 권한을 private로 변경
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # travis repo setting 설정값
    secret_access_key: $AWS_SECRET_KEY # travis repo setting 설정값
    bucket: mumuni-springboot-build
    key: mumuni-springbootToy.zip
    bundle_type: zip
    application: mumuni-springboottoy
    deployment_group: mumuni-springboottoy-group
    region: ap-northeast-2
    wait-until-deployed: true

# CI 실행 완료 시 메일 알람
notifications:
  email:
    recipients:
      - ohj8447@gmail.com